"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2026-03-28 09:26:02.511963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_crypto_currency_id'), 'crypto_currency', ['id'], unique=False)
    op.create_table('crypto_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('one_day_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['crypto_currency.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_crypto_tracker_id'), 'crypto_tracker', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_tracker_id'), table_name='crypto_tracker')
    op.drop_table('crypto_tracker')
    op.drop_index(op.f('ix_crypto_currency_id'), table_name='crypto_currency')
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###
